services:
  mongodb:
    image: mongo:latest
    container_name: vision-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vision-network

  redis:
    image: redis:alpine
    container_name: vision-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vision-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vision-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - vision-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vision-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - vision-network

networks:
  vision-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 